### ISSUE TITLE
unable to autoload plugin

### ISSUE THREAD

**Issue by soldivelot** [Kiyamou/VapourSynth-RealCUGAN-ncnn-Vulkan#1]
can not find this plugin when using `core.plugins()`

srmd works fine in same situation

**Comment by Kiyamou** [comment]
My test is normal.

Please provide more details and I will try to reproduce.

**Comment by soldivelot** [comment]
OS: win11 21H1 x64
VS: R59
Plugin: R2

files:
```
vapoursynth64\plugins\realcugannv.dll
vapoursynth64\plugins\models\models-nose\
vapoursynth64\plugins\models\models-se\
vapoursynth64\plugins\models\models-pro\
```

script:
```
clip = core.rcnv.RealCUGAN(clip=clip,model=1,scale=2,noise=3)
```

 error:
![图片](https://user-images.githubusercontent.com/84898012/182009856-905fb8e6-9314-4109-bc53-d71342ec1dba.png)

**Comment by Kiyamou** [comment]
I reproduced this problem on VapourSynth R59. It seems that some plugins have problems loading on new version VapourSynth. I need some time to figure it out.

Maybe you can try VapourSynth R57. I test on this version.

**Comment by realmp5** [comment]
Just to confirm that I've had the exact same issue.
Any chance of porting the RealBasicVSR when you have time?
https://github.com/ckkelvinchan/RealBasicVSR
It does have a very interesting crystal clear post-processed video/images.
Appreciate for all your works.

**Comment by dexzopiclone** [comment]
same issue.

CPU: AMD Ryzen 5 3600
OS: windows 10 21H2 x64
Py: Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)] on win32
VS: 'VapourSynth Video Processing Library\nCopyright (c) 2012-2021 Fredrik Mellbin\nCore R57\nAPI R4.0\nAPI R3.6\nOptions: -\n'

files:
plugins64\realcugannv.dll
plugins64\models\models-nose\
plugins64\models\models-se\
plugins64\models\models-pro\

```
C:\Users\user>python
Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import vapoursynth
>>> vapoursynth.core.version()
'VapourSynth Video Processing Library\nCopyright (c) 2012-2021 Fredrik Mellbin\nCore R57\nAPI R4.0\nAPI R3.6\nOptions: -\n'
>>> vapoursynth.core.std.LoadPlugin(r"C:\Users\user\AppData\Roaming\VapourSynth\plugins64\realcugannv.dll")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src\cython\vapoursynth.pyx", line 2580, in vapoursynth.Function.__call__
vapoursynth.Error: Failed to load C:\Users\user\AppData\Roaming\VapourSynth\plugins64\realcugannv.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.
```

I tried to move plugin dll file and models to a new document, and load by core.std.LoadPlugin(). it can't work.

**Comment by Kiyamou** [comment]
> same issue.
> 
> CPU: AMD Ryzen 5 3600 OS: windows 10 21H2 x64 Py: Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)] on win32 VS: 'VapourSynth Video Processing Library\nCopyright (c) 2012-2021 Fredrik Mellbin\nCore R57\nAPI R4.0\nAPI R3.6\nOptions: -\n'
> 
> files: plugins64\realcugannv.dll plugins64\models\models-nose plugins64\models\models-se plugins64\models\models-pro\
> 
> ```
> C:\Users\user>python
> Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import vapoursynth
> >>> vapoursynth.core.version()
> 'VapourSynth Video Processing Library\nCopyright (c) 2012-2021 Fredrik Mellbin\nCore R57\nAPI R4.0\nAPI R3.6\nOptions: -\n'
> >>> vapoursynth.core.std.LoadPlugin(r"C:\Users\user\AppData\Roaming\VapourSynth\plugins64\realcugannv.dll")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "src\cython\vapoursynth.pyx", line 2580, in vapoursynth.Function.__call__
> vapoursynth.Error: Failed to load C:\Users\user\AppData\Roaming\VapourSynth\plugins64\realcugannv.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.
> ```
> 
> I tried to move plugin dll file and models to a new document, and load by core.std.LoadPlugin(). it can't work.

Thanks for your test. I will try to figure out the changes caused by the update of the version and API of VapourSynth.

**Comment by Kiyamou** [comment]
> Just to confirm that I've had the exact same issue. Any chance of porting the RealBasicVSR when you have time? https://github.com/ckkelvinchan/RealBasicVSR It does have a very interesting crystal clear post-processed video/images. Appreciate for all your works.

To be honest, this project depends on the upstream project (realcugan-ncnn-vulkan). I don't know if I have the ability to port RealBasicVSR from Python to VapourSynth-ncnn.

**Comment by realmp5** [comment]
No prob.  Thanks for taking a look at it though!

**Comment by dexzopiclone** [comment]
By the way, upstream project has been updated. The vpy script doesn't support for pro module yet.  Hope somebody will fix it. 

Changelog:
2022-05-35: [Real-CUGAN-Pro](https://github.com/bilibili/ailab/blob/main/Real-CUGAN/Changelog_CN.md)；下载weights_pro参数+20220535更新包或完整包使用

Pro module preview:
https://github.com/bilibili/ailab/blob/main/Real-CUGAN/Changelog_CN.md

**Comment by Kiyamou** [comment]
@dexzopiclone 
I got the email notification about the models-pro. In fact, it has been supported in the R2 version. Just set `model = 2`.

**Comment by eapiova** [comment]
Any update? Still got the same problem on R57 and R61, both on LInux and on Windows

**Comment by atomsfear** [comment]
r1 depend on vcomp140.dll, r2 depend on vcomp140d.dll. Program build on debug config. Causing it to be unusable for users who do not have Visual Studio Build Tools installed.
